modLoader="javafml" #mandatory

loaderVersion="[33,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.

license="All rights reserved"

issueTrackerURL="http://my.issue.tracker/" #optional

[[mods]] #mandatory

modId="cac" #mandatory

version="1.16.2-1.0.6" #mandatory

displayName="Caves and Creatures" #mandatory

updateJSONURL="http://myurl.me/" #optional

displayURL="http://example.com/" #optional

logoFile="examplemod.png" #optional

credits="Thanks for this example mod goes to Java" #optional

authors="Love, Cheese and small house plants" #optional

description=''' '''

[[dependencies.examplemod]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[33,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.examplemod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.2]"
    ordering="NONE"
    side="BOTH"
